# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifySelector' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifySelector
  pod 'SpotifyLogin', '~> 0.1'
  pod 'Hero'
  pod 'TextFieldEffects'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'  

  target 'SpotifySelectorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotifySelectorUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'Spartan'
end
